version: '3.0'

services:
  db:
    image: postgres:14
    container_name: spring-batch-retry-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test