server:
  port: 9090
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  batch:
    initialize-schema: always
